#!/usr/bin/env python3
import sys
import json 
import datetime
import io

def main(args):
    if len(args) == 1:
        graphobj = json.loads(sys.stdin.read())
    else:
        graphfile = io.open(args[1])
        graphdata = graphfile.read()
        graphfile.close()

        graphobj = json.loads(graphdata)
    print('// Generated by graph2asy.')
    print('// Python Script written by Supakorn "Jamie" R. :)')
    print('// Created at {0}'.format(datetime.datetime.now()))
    print('')

    print('// header')
    print(graphobj['options']['header'])

    definededges = {}
    drawnedges = set()
    nodespos = {}
    edgeslist = []
    edgecount = 0

    print('')
    print('// options')
    print('real circrad=', graphobj['options']['circrad'],';')
    # print('pen filloptpen=', graphobj['options']['fillbackground'], ';')

    arrowstyle = graphobj['options']['arrowstyle']

    for nodes in graphobj['graph']:
        nodespos[nodes['id']] = nodes['pos']
        for outnodes in nodes['outnodes']:
            node_id = outnodes
            if isinstance(outnodes, dict):
                label_data = {'label': outnodes['label'], 'align':outnodes['align']}
                node_id = outnodes['id']
            else:
                label_data = None
            edgeslist.append((nodes['id'], node_id, label_data))

    print('// edges')

    # print('picture edgepic;')
    # edges
    for edge in edgeslist:
        print('// processing edge {0}'.format(edge))

        if ordtuple(edge) not in definededges:
            edgecount += 1
            edge_name = 'edge_{0}'.format(edgecount)
            print('path {0}={1}--{2};'.format(edge_name,
                                              tuple(nodespos[edge[0]]), tuple(nodespos[edge[1]])))
            curredge = edgecount
            definededges[ordtuple(edge)] = edgecount

            reversedEdge = False

        else:
            edge_name = 'edge_{0}'.format(edgecount)
            curredge = definededges[ordtuple(edge)]
            reversedEdge = True

        

        if graphobj['options']['directed']:
            lineProp = '1.0 - circrad/arclength({0})'.format(edge_name)
            print('draw({2}({0}),arrow=Arrow({3}Relative({1})));'.format(edge_name, lineProp,
                                                                         'reverse' if reversedEdge else '',
                                                                               arrowstyle + ',' if arrowstyle is not None else ''))
            if edge[2]:
                print('label("{1}",{0},align={2});'.format(edge_name, edge[2]['label'], edge[2]['align']))
        else:
            if ordtuple(edge) not in drawnedges:
                print('draw({0});'.format(edge_name))

                if edge[2]:
                    print('label("{1}",path={0},align={2});'.format(edge_name, edge[2]['label'], edge[2]['align']))
                drawnedges.add(ordtuple(edge))

        print('')

    # vertices
    print('')
    print('// vertices')

    for nodes in graphobj['graph']:
        postuple = str(tuple(nodes['pos']))
        print('// processing node id {0}'.format(nodes['id']))
        print('unfill(circle({0},circrad));'.format(postuple))
        print('draw(circle({0},circrad));'.format(postuple))
        print('label("{0}", {1});'.format(nodes['text'], postuple))
        print('')

def ordtuple(tup: tuple):
    tup = tuple([val for val in tup if isinstance(val,int)])
    return (min(tup), max(tup))

if __name__ == '__main__':
    sys.exit(main(sys.argv) or 0)
